# Generated by Django 3.2.3 on 2021-05-28 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SFH_REST', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='accounts',
            name='firstname',
            field=models.CharField(default='Vadim', max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='accounts',
            name='secondname',
            field=models.CharField(default='Muhtarullin', max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='accounts',
            name='username',
            field=models.CharField(default='Vadim', max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='clients',
            name='firstname',
            field=models.CharField(default='Vadim', max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='clients',
            name='secondname',
            field=models.CharField(default='Muhtarullin', max_length=64),
            preserve_default=False,
        ),
    ]
