# Generated by Django 3.2.3 on 2021-05-28 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SFH_REST', '0003_rename_email_salesfunnels_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='salesfunnels',
            old_name='username',
            new_name='AccountsID',
        ),
    ]
